### ISSUE TITLE
Write error when file contents not utf8 encoded

### ISSUE THREAD

**Issue by tgoodlet** [elmotec/massedit#10]
I get the following error if my input file corpus is not `utf8` encoded:
```
Traceback (most recent call last):                                      
  File "replace.py", line 50, in <module>                               
    dry_run=False,                                                      
  File "/home/tyler/repos/massedit/massedit.py", line 440, in edit_files
    diffs = list(editor.edit_file(path))                                
  File "/home/tyler/repos/massedit/massedit.py", line 202, in edit_file 
    new_file.writelines(to_lines)                                       
TypeError: must be unicode, not str                                     
```

A change to https://github.com/elmotec/massedit/blob/master/massedit.py#L202
resolves this:

`new_file.writelines(line.decode('utf8') for line in to_lines)`

I can provide a PR if necessary.

**Comment by elmotec** [comment]
Ok. I am not sure I understand the fix though.

I suppose utf-8 should not be hard-coded anyway. I'd rather add an option that specifies the encoding with utf-8 as default.

**Comment by elmotec** [comment]
Hey @tgoodlet, Could you attach a small example file that reproduces the problem, please? Just to make sure it's fixed for you at least.

**Comment by tgoodlet** [comment]
I can't seem to reproduce after reverting the change. I'll close this for now until I hit it again (if I ever do).

**Comment by elmotec** [comment]
No problem. I think it's not right to assume utf-8 for all input files. I've made changes to allow the user to specify the encoding. I'll polish and commit this week end.
